# SPDX-License-Identifier: MPL-2.0

name: CI
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1' # Latest stable
        os:
          - ubuntu-latest
        include:
          - version: '1'
            os: macOS-latest
          - version: '1'
            os: windows-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: julia-actions/setup-julia@4c0cb0fce8556fdb04a90347310e5db8b1f98fb9  # v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@d10a6fd8f31b12404a54613ebad242900567f2b9  # v2
      - uses: julia-actions/julia-buildpkg@e3eb439fad4f9aba7da2667e7510e4a46ebc46e1  # v1
      - uses: julia-actions/julia-runtest@6e050c8013b833b1195105ff2fce9cd802f53271  # v1
